NASA_DOCUMENTS = [
    {
        'title': 'Apollo 11 Mission Report',
        'url': 'https://archive.org/download/apollo-11-mission-report/apollo-11-mission-report.pdf',
        'filename': 'apollo_11_mission_report.pdf',
        'mission': 'Apollo 11',
        'year': 1969,
    },
    {
        'title': 'Apollo 13 Mission Report',
        'url': 'https://archive.org/download/apollo-13-mission-report/apollo-13-mission-report.pdf',
        'filename': 'apollo_13_mission_report.pdf',
        'mission': 'Apollo 13',
        'year': 1970,
    },
    {
        'title': 'Apollo 17 Mission Report',
        'url': 'https://archive.org/download/NASA_NTRS_Archive_19730015117/NASA_NTRS_Archive_19730015117.pdf',
        'filename': 'apollo_17_mission_report.pdf',
        'mission': 'Apollo 17',
        'year': 1973,
    },
    {
        'title': 'STS-1 Press Kit',
        'url': 'https://www.nasa.gov/wp-content/uploads/2023/05/sts-001-press-kit.pdf',
        'filename': 'sts_1_press_kit.pdf',
        'mission': 'STS-1 (First Shuttle Flight)',
        'year': 1981,
    },
    {
        'title': 'Voyager 1 Encounter with Jupiter',
        'url': 'https://archive.org/download/NASA_NTRS_Archive_19800008743/NASA_NTRS_Archive_19800008743.pdf',
        'filename': 'voyager_jupiter.pdf',
        'mission': 'Voyager 1 & 2',
        'year': 1979,
    },
    {
        'title': 'Hubble Space Telescope Servicing Mission 1',
        'url': 'https://archive.org/download/NASA_NTRS_Archive_19940015719/NASA_NTRS_Archive_19940015719.pdf',
        'filename': 'hubble_sm1.pdf',
        'mission': 'STS-61 (Hubble Repair)',
        'year': 1993,
    },
    {
        'title': 'Mars Pathfinder Landing Press Kit',
        'url': 'https://mars.nasa.gov/internal_resources/816/',
        'filename': 'mars_pathfinder.pdf',
        'mission': 'Mars Pathfinder',
        'year': 1997,
    },
    {
        'title': 'Mars Exploration Rover Landing Press Kit',
        'url': 'https://mars.nasa.gov/internal_resources/826/',
        'filename': 'mars_exploration_rovers.pdf',
        'mission': 'Spirit & Opportunity',
        'year': 2004,
    },
]
