NASA_DOCUMENTS = [
    {
        'title': 'Apollo 11 Mission Report',
        'url': 'https://archive.org/download/apollo-11-mission-report/apollo-11-mission-report.pdf',
        'filename': 'apollo_11_mission_report.pdf',
        'mission': 'Apollo 11',
        'year': 1969,
    },
    {
        'title': 'Apollo 13 Mission Report',
        'url': 'https://archive.org/download/apollo-13-mission-report/apollo-13-mission-report.pdf',
        'filename': 'apollo_13_mission_report.pdf',
        'mission': 'Apollo 13',
        'year': 1970,
    },
    {
        'title': 'Apollo 17 Mission Report',
        'url': 'https://archive.org/download/NASA_NTRS_Archive_19730015117/NASA_NTRS_Archive_19730015117.pdf',
        'filename': 'apollo_17_mission_report.pdf',
        'mission': 'Apollo 17',
        'year': 1973,
    },
    {
        'title': 'STS-1 Press Kit',
        'url': 'https://www.nasa.gov/wp-content/uploads/2023/05/sts-001-press-kit.pdf',
        'filename': 'sts_1_press_kit.pdf',
        'mission': 'STS-1 (First Shuttle Flight)',
        'year': 1981,
    },
    {
        'title': 'Voyager 1 Encounter with Jupiter',
        'url': 'https://archive.org/download/NASA_NTRS_Archive_19800008743/NASA_NTRS_Archive_19800008743.pdf',
        'filename': 'voyager_jupiter.pdf',
        'mission': 'Voyager 1 & 2',
        'year': 1979,
    },
    {
        'title': 'Hubble Space Telescope Servicing Mission 1',
        'url': 'https://archive.org/download/NASA_NTRS_Archive_19940015719/NASA_NTRS_Archive_19940015719.pdf',
        'filename': 'hubble_sm1.pdf',
        'mission': 'STS-61 (Hubble Repair)',
        'year': 1993,
    },
    {
        'title': 'Mars Pathfinder Landing Press Kit',
        'url': 'https://mars.nasa.gov/internal_resources/816/',
        'filename': 'mars_pathfinder.pdf',
        'mission': 'Mars Pathfinder',
        'year': 1997,
    },
    {
        'title': 'Mars Exploration Rover Landing Press Kit',
        'url': 'https://mars.nasa.gov/internal_resources/826/',
        'filename': 'mars_exploration_rovers.pdf',
        'mission': 'Spirit & Opportunity',
        'year': 2004,
    },
    {
        'title': 'Commercial Crew Program Press Kit',
        'url': 'https://www.nasa.gov/wp-content/uploads/2015/10/commercial_crew_press_kit_2.pdf',
        'filename': 'commercial_crew_press_kit.pdf',
        'mission': 'Commercial Crew (Crew Dragon / Starliner)',
        'year': 2022,
    },
    {
        'title': 'Mars 2020 Launch Press Kit',
        'url': 'https://www.jpl.nasa.gov/news/press_kits/mars_2020/download/mars_2020_launch_press_kit.pdf',
        'filename': 'mars_2020_launch_press_kit.pdf',
        'mission': 'Mars 2020 / Perseverance',
        'year': 2020,
    },
    {
        'title': 'Mars 2020 Landing Press Kit',
        'url': 'https://mars.nasa.gov/system/downloadable_items/45585_mars_2020_landing_press_kit.pdf',
        'filename': 'mars_2020_landing_press_kit.pdf',
        'mission': 'Mars 2020 / Perseverance',
        'year': 2021,
    },
    {
        'title': 'Ingenuity Mars Helicopter Landing Press Kit',
        'url': 'https://www.jpl.nasa.gov/news/press_kits/mars_2020/download/ingenuity_landing_press_kit.pdf',
        'filename': 'ingenuity_press_kit.pdf',
        'mission': 'Ingenuity',
        'year': 2021,
    },
    {
        'title': 'JWST Launch Media Kit',
        'url': 'https://science.nasa.gov/wp-content/uploads/2024/08/webbmediakit.pdf',
        'filename': 'jwst_media_kit.pdf',
        'mission': 'James Webb Space Telescope',
        'year': 2021,
    },
    {
        'title': 'Artemis I Press Kit',
        'url': 'https://www.nasa.gov/wp-content/uploads/static/artemis-i-press-kit/img/Artemis%20I_Press%20Kit.pdf',
        'filename': 'artemis_i_press_kit.pdf',
        'mission': 'Artemis I',
        'year': 2022,
    },
    {
        'title': 'Artemis I Reference Guide',
        'url': 'https://www.nasa.gov/wp-content/uploads/static/artemis-i-press-kit/img/Artemis%20I%20Reference%20Guide_Inter.pdf',
        'filename': 'artemis_i_reference_guide.pdf',
        'mission': 'Artemis I',
        'year': 2022,
    },
    {
        'title': 'Artemis II Press Kit',
        'url': 'https://www.nasa.gov/wp-content/uploads/2026/01/artemis-ii-press-kit.pdf',
        'filename': 'artemis_ii_press_kit.pdf',
        'mission': 'Artemis II',
        'year': 2025,
    },
    {
        'title': 'Artemis II Reference Guide',
        'url': 'https://www.nasa.gov/wp-content/uploads/2026/01/a2-reference-guide-012825.pdf',
        'filename': 'artemis_ii_reference_guide.pdf',
        'mission': 'Artemis II',
        'year': 2025,
    },
    {
        'title': 'ISS Expedition 25/26 Press Kit',
        'url': 'https://www.nasa.gov/wp-content/uploads/2023/06/expedition25-26-presskit.pdf',
        'filename': 'iss_expedition_25_26_presskit.pdf',
        'mission': 'ISS Expedition 25/26',
        'year': 2010,
    },
]
